module.exports = [
  'You’re very beautiful',
  'You’re very pretty',
  'You look as pretty as always',
  'You’re so adorable',
  'You look drop dead gorgeous',
  'You have the most beautiful eyes',
  'I think you’re very attractive',
  'Wow, you’re gorgeous',
  'I think you’re stunning',
  'I think you’re super cute',
  'You look so radiant',
  'You look absolutely fantastic',
  'You look great',
  'You’re beyond gorgeous',
  'Watching you is like listening to angels sing',
  'You look out of this world',
  'You make my heart melt',
  'I can’t take my eyes off of you',
  'Your smile melts my heart',
  'I think you’re the most beautiful person in the world',
  'I have never seen anyone as beautiful as you',
  'Your beauty is incomparable',
  'You look like an angel',
  'You’re very handsome'
]
